### ISSUE TITLE
(bug?) should we fall back in body parsing when deserialization fail?

### ISSUE THREAD

**Issue by mickeyn** [PerlDancer/Dancer2#1056]
When we fail to deserialize body content, we fall back to the "regular" body parsing (through Plack::Request) - this may lead to unexpected results (we're reading the content not as intended).

Shouldn't we settle for an error / empty body when we have a serializer set and we fail to deserialize the body?

example:

``` perl
package MyApp;
use Dancer2;
set serializer => 'JSON';
post '/' => sub { +{ xxx => body_parameters->get('xxx') } };
1;
```

with valid JSON:

```
$ curl -q -X POST -d'{"important":"# DANGER!!! NEVER set xxx/yyy/etc. (i.e. yyy=1;xxx=1;...)"}' http://0:3000
{"xxx":null}
```

with invalid JSON (removed the last '}'):

```
$ curl -q -X POST -d'{"important":"# DANGER!!! NEVER set xxx/yyy/etc. (i.e. yyy=1;xxx=1;...)"' http://0:3000
{"xxx":"1"}
```

**Comment by mickeyn** [comment]
forgot to mention this also comes with server log errors for the failed deserialization (as expected).

**Comment by veryrusty** [comment]
@mickeyn++ I'm not keen on the current behaviour and would like to see this cleaned up (or at least simplified). I've been considering (but lacked the tuits to try) reversing the current order, and doing (roughly):
  * If the request is `application/x-www-form-urlencoded` or `multipart/form-data`, then let HTTP::Body or similar do its thing, otherwise
  * let the serializer engine (if defined) do its thing, which includes die on failure.

**Comment by mickeyn** [comment]
@veryrusty: I think it's bad if the server dies on failure to deserialize esp. in the case of invalid user input.

**Comment by veryrusty** [comment]
@mickeyn I meant "let the serialization die".  One day I'll learn to English ;)

I've taken a first pass at implementing what I proposed above. I'll clean it up and push it for review later in the week.

**Comment by mickeyn** [comment]
@veryrusty cool!

**Comment by xsawyerx** [comment]
@veryrusty Is there a PR for that branch anywhere?

**Comment by veryrusty** [comment]
@xsawyerx not yet, I got distracted with seasonal festivities.  I need to go back over it; from memory its the docs that are lacking :(

**Comment by cwallacetlc** [comment]
I think I'm currently struggling with this issue.  We have an AJAX API section of our website mounted to '/api' with a JSON serializer.  But when we issue AJAX requests to it, the browser sends them as application/x-www-form-urlencoded rather than JSON.  This used to work, with Dancer2 0.152000, but now that we've upgraded to 0.207000, it's trying to decode the body as JSON and dying.

If we can get the functionality mentioned by @veryrusty above, we won't need to rework all our AJAX requests.

Anything I can do to help?

**Comment by veryrusty** [comment]
We no longer use HTTP::Body (PR #1406), and now throw a '400 Bad Response' if the serialization fails #1509. There is no longer any fallback if a serializer is defined and the body fails to be deserialized.

Resolving 4.5 years later .. apologies @mickeyn !

**Comment by mickeyn** [comment]
@veryrusty++ :)
