### ISSUE TITLE
dzil test changes README.mkdn

### ISSUE THREAD

**Issue by szabgab** [PerlDancer/Dancer2#1057]
I just ran ```dzil test``` and it modified README.mkdn

If it is an auto-generated file then I think it should not be committed to git.

**Comment by xsawyerx** [comment]
It is required to be in the Git repo so Github will show it when you access the page. That part is by design.

It's generated by [Dist::Zilla::Plugin::ReadmeFromPod](https://metacpan.org/pod/Dist::Zilla::Plugin::ReadmeFromPod). We cannot change this, so I recommend opening a ticket for it creating it on `dzil test` on the appropriate [Github repo](https://github.com/fayland/dist-zilla-plugin-readmefrompod).

Thanks.
