### ISSUE TITLE
Allow the configuration of templating system during run-time

### ISSUE THREAD

**Issue by szabgab** [PerlDancer/Dancer2#1059]
e.g. in the ```before``` hook. by somthing like this:
```
hook before => sub {
    my $appdir = abs_path config->{appdir};
    set engines => {
        template => {
            template_toolkit => {
                start_tag => '<%',
                end_tag   => '%>',
                INCLUDE_PATH => path($appdir, 'templates'),
            }
        }
    };
    set template => "template_toolkit";
};
```

**Comment by xsawyerx** [comment]
The reason you can't set it in a `before` hook is because it's **request-time**. In fact, you **are** setting it, but the engine doesn't have the current request. If you were to call the `set_request`, it will work:

    app->template_engine->set_request( request );

When a request begins, we set the current request in every engine. If you change it in the `before` hook it means we have to check for this after every `before` hook called. I don't like it, to be honest. I already think it's too dynamic. I would prefer the template to be set at compile time and not altered later.

If there are enough votes, I'm willing to change it, but otherwise I prefer not to. Mainly because I really don't see a reasonable use-case for it. I'm more than happy to be proven wrong.

**Comment by szabgab** [comment]
I found another solution to my problem.

**Comment by xsawyerx** [comment]
@szabgab Could you please share your problem and the solution you found?
