### ISSUE TITLE
Dancer2 messes my encoding

### ISSUE THREAD

**Issue by Grimy** [PerlDancer/Dancer2#1122]
Running the following UTF-8 encoded source file:

    #!/usr/bin/perl -l
    print 'février';
    use Dancer2;
    print 'février';

Produces the following results:

    février
    f�vrier

hexdump reveals that “�” is actually “\xe9”, which is latin1 for “é”.

A grep through Dancer2’s source reveals the responsible line:

    $clean_import
        or $_->import::into($caller) for qw<strict warnings utf8>;

Please don’t do this. Silently messing with your caller’s encoding is never a good idea.

Of course, removing it now risks breaking some callers, so instead I suggest documenting it. Dancer2::Manual currently says:

    strict and warnings pragmas are also imported with Dancer2

It should instead say:

    strict, warnings *and utf8* pragmas are also imported with Dancer2

That would have saved me hours of debugging.

**Comment by veryrusty** [comment]
I'll get the doc patch merged asap. I thought it was documented, but looks like it never was. Sorry it caused you so much pain.

Perl's internal representation of the UTF-8 e-acute character is a single byte (\xe9). Using characters than have multibyte representations, such as the snowman U+2603 or the skull and crossbones U+2620 glyphs (or something else you prefer) is a better approach when testing. e.g.
```
#!/usr/bin/perl -l
print 'février'';
print 'février ☃'';
use Dancer2;
print 'février'';
print 'février ☃'';
```

The output is dependent on STDOUT expecting byte or character strings. I'm expecting you'll get a  `Wide character in print` warning (which the e-acute doesn't trigger), hinting that STDOUT is expecting (UTF-8) byte rather than character strings. You can also verify this with a oneliner (with and without the '-CO' flag: `perl -CO -Mutf8 -E'say "février ☃"'`

**Comment by Grimy** [comment]
> I'll get the doc patch merged asap.

Thank you.

> Perl's internal representation of the UTF-8 e-acute character is a single byte (\xe9)

No. Perl's internal representation of the UTF-8 e-acute character is two bytes: `"\0303\0251"` (hexa `"\xC3\xA9"`). Try:

    perl -MDevel::Peek -e 'Dump "é"; use utf8; Dump "é"'

Both print out `PV = (…) "\303\251"`; only the UTF8 flag changes.
