### ISSUE TITLE
Encoding of body_params vs param/params

### ISSUE THREAD

**Issue by patzim** [PerlDancer/Dancer2#1192]
- Dancer2 v0.200001
- _config.yml_ has `charset: "UTF-8"` set.
- When doing

        my @params = (Empfänger => '毛泽东');
        $user_agent->post(
            $url,
            'Content-type' => "application/x-www-form-urlencoded; charset='utf8'",
            Content      => [ map { Encode::encode_utf8( $_ ) } @params ],
        );

- `params` returns

        { Empfänger => '毛泽东' }

- and `body_parameters` returns

        { EmpfÃ¤nger => 'æ¯æ³½ä¸' }

- When doing a `map { Encode::decode( "utf-8", $_) }` on that I get the decoded version.

I tracked `params` down to Request.pm:312: `$self->_params` which is initialized in line 460 with `$self->_body_params` wich does a `_decode` in line 125.

And `body_parameters` in _Request.pm:368_: `return $self->env->{'plack.request.body'}`.

I am rather unskilled with providing good information. So if I should provide more (which?) information, please say so!

**Comment by SysPete** [comment]
Looking at code and tests (t/dsl/parameters.t) this actually looks intentional though I have not (yet) found anything in the docs that mentions this difference.

@PerlDancer (especially @xsawyerx) I've been hunting through the various issues and PR #988 but I can't find any discussion or explanation for this particular difference between params and parameters. Can anyone help enlighten us?

**Comment by SysPete** [comment]
@patzim many thanks for spending the time to submit this detailed issue. I've created PR #1219 which addresses it.

**Comment by cromedome** [comment]
Fixed in 1d62e519017faed3ae0e22ab2578592f46795c30. Closing.
