### ISSUE TITLE
sessions can not be flushed

### ISSUE THREAD

**Issue by drmuey** [PerlDancer/Dancer2#1276]
Howdy Dancer2 folks!

w/ Dancer2 v0.204000 and Dancer2::Session::JSON v0.002 I have the following:

I have an app whose config.yml is ```session: "JSON"``` and session() returns an ```Dancer2::Core::Session``` object.

I am getting a race condition where I change the session w/ something like ```session foo => 42;``` but the session is dirty so the next redirected-to route does not always see session('foo') as 42.

I want to ```session->flush();``` before redirecting but when I do I get ```Can't locate object method "flush" via package "Dancer2::Core::Session" at …```

I suspect I am missing something stupid obvious … Any thoughts?

**Comment by veryrusty** [comment]
`Dancer2::Core::Session` encapsulates anything related to a specific session: its ID,
its data, and its expiration; but is completely agnostic of how the session is stored.

The session engines (anything that consumes `Dancer2::Core::Role::SessionFactory`) handle session  store, create, retrieve, flush and destroy.

Normally Dancer2 uses an [after_request](https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/Core/App.pm#L692-L738) hook to do session flushing. If you have a session object in a route handler,
```
$session->is_dirty && $app->session_engine->flush( session => $session )
```
(where `$app` is passed as the first parameter to the route) will flush the session.

**Comment by drmuey** [comment]
cool thanks ;)

**Comment by drmuey** [comment]
Here is how to do it for anyone coming here w/ the same problem, thanks again @veryrusty!

Note that the first, and only, argument to the code ref is the response object and not the app object.

```
+hook after_request => sub {
+    my $app = app();
+    my $ses = session();
+    $ses && $ses->is_dirty && $app->session_engine->flush( session => $ses );
+};
```

**Comment by hvoers** [comment]
This should be automatic.
No one should be forced to write this.
I want a session that just does its thing.

**Comment by xsawyerx** [comment]
@hvoers I think you're missing the problem here.

Dancer actually does a smart thing regarding sessions. I would be surprised if it's the only framework that does it, to be honest.

What Dancer does is store two levels of sessions.

The first is the actual storage. That storage can be memcache, a DB, etc. It has an adapter under the `Dancer2::Session::` namespace. `Dancer2::Session::JSON` is an adapter to a file-based storage using the JSON format.

The second level is an abstraction over session information and maintains a session object for the duration of a request. This is `Dancer2::Core::Session`. It maintains information in a hash, as @veryrusty explained above. At the end of a request cycle, Dancer syncs that with the actual session storage (this is what the **flush** means).

If Dancer would have not have done this, every time you tried storing something in a session, every single request to `session` would result in a write and an I/O operation. Every time you would read something from a session, it would result in a read and an I/O operation. Instead, Dancer aggregates these and "caches" it (not really caching, but during the request cycle, yes).

I honestly dislike seeing a :-1: in what seems to be a misunderstanding of what how this mechanism works and **why** it exists.

As far Dan's case:

There is an inherent problem with this situation. You have multiple concurrent requests that synchronize with `session` through their concurrent cycle. This is bound to fail. This can fail for other reasons too. If a request that causes a change in how other requests will work, it is reasonable to assume that until the request has finished, it will not have made the request, but in your case you want it to 1. Make a change, and 2. Have it apply before it finished. This is a problematic situation.

We could introduce a `autoflush` feature which changes the behavior to flush as soon as a write happens, but this doesn't change any design that does not consider the requests atomic and instead needs requests to make changes and have them apply before they're finished because there are concurrent requests that need that information.

I would be more than happy to help figure out how to do this better, since this seems to me like a problematic design.

**Comment by xsawyerx** [comment]
Last note: The way the current session works is that all session writes are *atomic*, allowing you to provide multiple writes that will end up being a singular atomic write. That's a design decision which carries a lot of strength in it when you understand it and utilize it.

**Comment by hvoers** [comment]
Sorry for not understanding the problem.
I read "Normally Dancer2 uses an after_request hook to do session flushing." as something we all must do.
That's not normal.
So, yes, I do not understand this. Sorry.

**Comment by xsawyerx** [comment]
My response was probably over-zealous. I apologize.

Do you think we should provide a way to do "hot piping", where we flush it every time you write to a session? I have encountered one session engine that could use it, because it wasn't able to fetch the data in one action, but each single value required a subroutine call. In most engines you fetch the entire thing in one subroutine call and it gets saved in the Session hash.

**Comment by drmuey** [comment]
@xsawyerx 

Not sure if this will help or not but FWiW:

My use case its not really a concurrency issue.

One person in one browser:

1. hits /foo
2. that route then:
    1. ```session foo => 42;```
    2. ``redirect uri_for('/bar')```
3. /bar usually sees foo as 42 but occasionally not

adding the flush-em-if-you-got-em after_request hook makes /bar always see the new foo, at least so far.

**Comment by xsawyerx** [comment]
This is bizarre. Can you run it without the manual flushing and see if there's a cookie for the session? If you set it, it should be available every time the user reaches the page.

I can imagine a situation where someone reaches the website, receives a single page that contains several resources. Then one of the resources tries to set a session that the other resources try to reach *using* the data from the session - that is a race condition. But that's not what you're describing so I'm very surprised by this.

This sounds more like a bug than unsupported behavior.

**Comment by ourmaninindia** [comment]
I really appreciate the above discussion but please do incorporate flushing in the manual. I was lost for hours not understanding why my session was not being stored  :(

**Comment by xsawyerx** [comment]
@ourmaninindia What phrasing - and where - would have helped you?

**Comment by ourmaninindia** [comment]
???  If it is listed in the manual under sessions one would know how this works. I was creating a progress bar in one place and a call from another place to monitor the updates. Thanks only to the above discussion i understood that I had to put a flush command in and it all works like a dream now.

**Comment by drmuey** [comment]
@xsawyerx sorry this fell through the cracks, I'll try to undo my fix locally and get more specifics on the state of the cookie/session/ thanks!
