### ISSUE TITLE
XML Serializer

### ISSUE THREAD

**Issue by jahagirdar** [PerlDancer/Dancer2#1297]
The Dancer2 Manual indicates that the XML Serializer is available.... 
Looking into https://github.com/PerlDancer/Dancer2/tree/master/lib/Dancer2/Serializer I do not find a XML.pm module.

I tried sending an XML fragment using the following code
```
 send_as  XML => $feed,{ content_type => 'application/xml; charset=UTF-8'};
```
This resulted in the following error
```
Unable to load serializer class for XML: Can't locate Dancer2/Serializer/XML.pm in @INC (you may need to install the Dancer2::Serializer::XML module)
```

**Comment by xsawyerx** [comment]
Currently there is no XML serializer, but as soon as there is one, the module would work just the same with it by loading the appropriate serializer and using it.

If you're interested in writing such a serializer, I'm sure others would appreciate it. I'm renaming this ticket to creating a serializer instead of asking if one exists.

**Comment by realflash** [comment]
I've done this, and it's in CPAN now.

**Comment by xsawyerx** [comment]
@realflash: Way to go! :)

With this, closing issue.
