### ISSUE TITLE
App::Cmd is a quite a heavy (mostly optional) dependency

### ISSUE THREAD

**Issue by JRaspass** [PerlDancer/Dancer2#1319]
The dancer2 CLI tool uses App::Cmd, which makes sense, however having the whole distribution depend on it doesn't make all that much sense. My motivation for this is to have less dependencies in my containers at $work that aren't even needed at runtime.

Two options jump out at me, we could make App::Cmd a recommended dependency and have the CLI tool die on invocation with a nice error message.

Alternatively it might be feasible to spin out the CLI tool to its own distribution.

Either way I feel the dancer2 CLI tool is handy for bootstrapping your web app, but isn't really needed after that, and certainly isn't needed on production.

I'd welcome any and all thoughts on this matter.

**Comment by xsawyerx** [comment]
Ah! I have a lot of thoughts on this. Mainly, I agree `App::Cmd` is heavy and big in dependencies.

The reason we have it is because we wanted to expand on this tool to allow more advanced options, like profiles, additional commands, etc. Unfortunately we never really got around to it.

There are in fact three options:
* Make it optional: I don't think it's a good idea.
* Move it to a different distribution, released separately: I don't think this is wise either. Users expect the minter to be part of it.
* Remove `App::Cmd` in favor of a lighter (possibly in-house) implementation. Honestly, this seems like the best solution IMHO.

What do you think?

**Comment by JRaspass** [comment]
Ooo I hadn't thought of option three. I haven't read the CLI/Command/*.pm files in detail yet, but I don't think we're using much of the features of App::Cmd, a port **should** be fairly trivial.

**Comment by xsawyerx** [comment]
Additionally, there's also [MooX::Options](https://metacpan.org/pod/MooX::Options) which can be inspected a possible replacement. It's a bit big, but I think it mostly shared what Dancer2 uses anyway.

**Comment by cromedome** [comment]
In the spirit of using what we can from CPAN, I would be in favor of `MooX::Options` if we are to move to anything different.

**Comment by racke** [comment]
Either App::Cmd or the way we are using it has IMHO serious flaws for a CLI program:

- doesn't complain about unknown options
- using -d ~/myapp results in creating home/racke/myapp in the current directory

**Comment by SysPete** [comment]
As mentioned to me by @cromedome, https://metacpan.org/pod/CLI::Osprey might be a reasonable option since it is pure-Perl and has an extremely light dep chain that doesn't force us above Perl 5.10

**Comment by cromedome** [comment]
Resolved by #1608. Thanks for the suggestion!
