### ISSUE TITLE
Dependency on Types::Standard not declared

### ISSUE THREAD

**Issue by veryrusty** [PerlDancer/Dancer2#1515]
Dancer2::Core::Types extends `Types::Standard`, but we do not list Type::Tiny or Types::Standard as a dependency.   I suspect an upstream dependency changed, exposing this.

You can verify with a clean perl install or use Docker to makes it easy: `docker run --rm -ti perl:5.14 cpanm -v Dancer2`.

**Comment by cromedome** [comment]
Fixed in #1516. Closing!

**Comment by haarg** [comment]
Type::Tiny was previously listed as a dependency, so while this change is fine, it wouldn't fix any actual problems.

If this was in reaction to `Undefined subroutine &Types::Standard::Str` errors, that was caused by Role::Tiny 2.000007.  Role::Tiny 2.000008 has been released which should fix this by reverting to the behavior of 2.000006.

**Comment by cromedome** [comment]
Thanks for the assist, @haarg - I appreciate you jumping in to help make sure future Dancer2 installs succeed!

**Comment by veryrusty** [comment]
Thank you @haarg !
