### ISSUE TITLE
Setting template and engines with set work incorrect

### ISSUE THREAD

**Issue by TheAthlete** [PerlDancer/Dancer2#574]
Hello!
 I can't set the parameters of engines and template using the set keyword, if you set these options, goes in such sequence:

set template => '...';
set engines => {};

the parameters of the engines are not installed. If in such sequence

set engines => {};
set template => '...';

then everything is fine.
 But if I use templates in DATA sections, the options parameter settings using configuration files or by importing them (ie. use Dancer2 template => 'haml') are not suitable, as in the path variable template, you must specify the virtual path (hash), for example using the Data::Section::Simple

**Comment by rleir** [comment]
Was there any development here in the last year? If it is just a question, then the users list will help. If not, then I would like to see a better example of code that shows the problem. Thanks!

**Comment by xsawyerx** [comment]
The problem here is that the order creates the templates and only then changes all the definitions on how to create a template. This needs to be reversed. First you set the variables for the template you will create and then you create the template.

Calling `set template => 'new_value'` triggers creating a template object from the values that are currently available in the configuration.
