### ISSUE TITLE
to_json masks exceptions thrown by JSON

### ISSUE THREAD

**Issue by LionsPhil** [PerlDancer/Dancer2#644]
`JSON::to_json` will die if you pass it objects without its `allow_blessed` options. Dancer's `to_json` keyword wrapping this masks these exceptions. It is not clear if this is intentional or a documentation omission (drilling down through the code I can't see where the exception is actually being caught). It seems more correct to me that it should not mask them, since the effect of returning undef in the most common use case:
```perl
return to_json { some => $structure };
```
...is that Dancer will get a `return undef` and serve a 200 OK response, when your application has encountered a bug and should (probably) be serving its HTTP 500 page.

You can reproduce this trivially by taking the default `dancer -a` app and replacing the route handler with:
```perl
my $object = bless({}, 'oops');
my $json = to_json { oops => $object };
warn "JSON response isn't defined" unless defined $json;
return $json;
```
Which will emit a warning and server a zero-byte document with status 200. Compare to replacing the `my $json` line with using JSON directly:
```perl
use JSON qw();
my $json = JSON::to_json { oops => $object };
```
Which will serve a 500 page and log that the route threw an exception.

**Comment by xsawyerx** [comment]
A 500 error indicates there is a problem with the application code (or with the server) and this seems like it's either developer error (there is no HTTP status for such a thing, sort of) or a bad request, which is a 400.

However, it would not be clear if the problem occurred because of the former or latter or sending a 400 automatically tells the user they screwed up, when in fact it could have been something the developer was doing.

On a `deserialize`, it is the user's fault, most likely. However, blowing up and returning a 400 does not provide the developer with an opportunity to do something about this.

On a `serialize`, it's the developer returning something bad and thus should not return a 400.

I vote to close the issue.

**Comment by LionsPhil** [comment]
I'm not sure I follow your comment, because the problem is you'll actually get a "successful" 200 status if you're doing `return to_json($something_unserializable)`, which is certainly wrong, and no warning or error is logged. (I haven't looked at if there's been any change in this area recently.)

If you intend `to_json` to mask exceptions and not be used like this, I think the bugfix is just documenting this (since it's an unexpected difference from `JSON::to_json`).

**Comment by xsawyerx** [comment]
I was looking at it from the serializer perspective. The serializer shouldn't crash on this.

**Comment by LionsPhil** [comment]
Right. I certainly agree that the *deserializer* shouldn't. If I've set up a serializer and my route has given it unserializable content, though, then that is an application bug IMO and ought to be throwing/warning the same way as if the route died. Returning 500 here doesn't seem any more wrong to me than getting a 500 because, say, someone tried to call a method on an undef reference because they failed to check that some model lookup actually found the record they were after.

**Comment by xsawyerx** [comment]
#972 was merged, which finally addresses this issue.

We really appreciate the help raising the issue, discussing it, exposing it, and analyzing and reasoning about it. It was tremendously helpful. And it was tremendously patient. :)
