### ISSUE TITLE
Default behavior for logger?

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/Dancer2#757]
What should be the default behavior if no logger has been specified? Do we want the STDERR logger, do we want the capture logger?

What do you think?

**Comment by yanick** [comment]
STDERR++  for two reasons. One, that's the default behaviour most would expect. Two: using the Capture log is a sure way to set a memory leak for most of the applications. Since there is no output, most peeps who wouldn't have read the docs closely will have no idea it's logging, and will have a heck of a nasty surprise as the memory usage grows and grows and grows. :-)

Btw, that's kinda related to perldancer/Dancer#1040

**Comment by sakshee3** [comment]
As I can see in the Core::App::_build_default_config, 'console' is already the default valiue. Am I missing anything ?

**Comment by cromedome** [comment]
Default logger is currently console, and from what I have mined from GitHub, since most people want the default to be STDERR, I am considering this resolved. Closing... thanks all!
