### ISSUE TITLE
Add serializer breaks Dancer2 app 

### ISSUE THREAD

**Issue by logust79** [PerlDancer/Dancer2#833]
Hello, 
I browsed through the current live issues, and am not sure whether this is relevant to any one of them.

    dancer2 -a webapp

Then set serializer as JSON in config.yml, localhost:3000 turns to blank. The error it gives is:

Failed to serialize the request: hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at …/lib/site_perl/5.18.1/JSON.pm line 154. in (eval 802) l. 2

What’s more, when set serializer in the config file, whenever a 404 error occurs, it stops looking for the 404 file in the public folder. Instead, it plainly throws an error object to the browser. 

These all began with version 0.158. It used to be okay with version 0.150.

Any idea?

Jing

**Comment by xsawyerx** [comment]
I'm sorry for missing this issue until now.

The reason is very simple. The scaffolded app implements a main endpoint (`/`) which renders a template. The template is an HTML string.

When you enable a serializer, you're saying you would like to serialize the output using that. Enabling the JSON serializer will ask Dancer2 to render your output to JSON. The error you're seeing is `JSON.pm` (the module used by the `Dancer2::Serializer::JSON` serializer) failing to serialize your HTML string (returned from the `template` keyword which is called in the `/` endpoint the `dancer2` app scaffolded for you) into JSON.

You will need to return a structure that `JSON` supports, like an arrayref or hashref.

**Comment by xsawyerx** [comment]
The following Advent Calendar contains more information: http://advent.perldancer.org/2014/11.
