### ISSUE TITLE
No after hook executed after redirect means no session (e.g. dancr.pl example fails)

### ISSUE THREAD

**Issue by bigpresh** [PerlDancer/Dancer2#840]
Krys006 on #dancer was having issues with the tutorial dancr.pl from Dancer2::Tutorial - he could submit the login form, and saw the splash login message, but the login link remained (instead of logout), and there was no form to add an entry.

A bit of investigation showed that no `Set-Cookie` header was being sent, so there was no session in the next request (although - I'm puzzled how the splash message worked, now I come to think of it, but that's another matter).

The dancr.pl code does:

```perl
            session->write('logged_in' => true);
            set_flash('You are logged in.');
            return redirect '/';
```

Changing it to return some content, rather than a redirect, solved the issue - a Set-Cookie header was sent, establishing a session, and everything worked as expected after that.

A bit more digging showed that `after` hooks don't appear to run after requests which perform a redirect.  I can't see why that should be the case - and that sounds like the bug to fix?

(In dancr.pl I added:

```perl
hook after => sub {
    warn "After hook executing for request to " . request->path;
};
```

... I would see it execute for "/", then for "/login" (requesting the login form), but after submitting the login form, I'd see it execute only for "/" (when the browser re-fetches the main page), but *not* for "/login" when the login form was actually submitted.)

Possible that this is related to #811 (as a cause)?

**Comment by bigpresh** [comment]
I note that the implementation of `redirect` claims:

```perl
    # Short circuit any remaining before hook / route code
    # ('pass' and after hooks are still processed)
    $self->has_with_return
        and $self->with_return->($self->response);
```

Seems that comment may be a lie :)  I'm not familiar enough with D2's low-level guts and Return::MultiLevel to figure it out at this moment, so I'd very much appreciate input from anyone who can help?

**Comment by veryrusty** [comment]
@bigpresh The after hook is being called - there are explicit tests for this in the test suite.

The reported symptoms are due to the session implementation being "lazy". We try not to create a session object unless we "need" it; as such, the session object is only set in the engine objects if the `session` keyword is used.

The route for `/` in the tutorial does not call `session`, hence no session object is instantiated or set in the template engine before the template is rendered. (This is may well be what was being seen in #811.)

There has to be a more friendly way than expecting users to call `session` before rendering a template that involves rendering session data, but at the same time keeping the session implementation as lazy as possible.

**Comment by bigpresh** [comment]
Well, my test in my test app suggested the after hook did *not* get called for the request that was redirected.

As for the implementation being lazy - I can see the value in not creating new sessions all the time if they're not being used, but perhaps a mid-way point would be to always create a session object if the request contained a session ID?  Thoughts?

**Comment by veryrusty** [comment]
I'm thinking that a call to the `template` keyword can instantiate the session object if it hadn't been done within route code. I'll put a Pr together :)

**Comment by xsawyerx** [comment]
#842 has been merged. Thanks! :+1:
