### ISSUE TITLE
PUT request with JSON array in body stops the request processing

### ISSUE THREAD

**Issue by utrack** [PerlDancer/Dancer2#844]
Dancer2 version: current CPAN

PUTting an JSON array fails with error:

    Internal Server Error
    Not a HASH reference at /usr/share/perl5/site_perl/Dancer2/Core/Request.pm line 483.

`_body_params` is expected to be hashref, when serializer returns an arrayref. 
Some proper warning would do.

**Comment by veryrusty** [comment]
When a serializer is set we try and serialize any data into the response. We really should handle deserializing any data type from the request body too.

If the deserailized data is a hashref, merge it into the request params. Otherwise we could
  * turn it into a key-value pair, and merge something like  `{ data => $deserialized_body_content }` into the request params, or
  * don't merge the deserialized data into the request params, leaving it in request->data. (my preferred option)
  * throw an error as @utrack suggested.

Does anyone else have an opinion on how this should be handled ?

**Comment by corecache** [comment]
As for option 2, the original request-> data gets lost when beeing overriden by the deserialized data? or did you mean to put the deserialized data into a separate attribute?

**Comment by veryrusty** [comment]
@corecache The "original" request body is always available via `request->body`.  `request->data` is a separate attribute that is populated with deserialized content

For the second option, an `if ( ref $data eq 'HASH' )` block wrapped around [lines 280-281 of Dancer2::Core::Request](
https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/Core/Request.pm#L280) should almost fix it (there is some documentation to clean up and a test or two to write as well :smile: )

**Comment by corecache** [comment]
@veryrusty That would at least make sure that everything which should get merged down into _body_params is a hash. This still leaves people who want to parse a JSONArray with having to access request->data instead of request->params/params.

1) Is there a valid and convenient way to have JSONArray acessible via params? 
2) is it needed afterall? 
3) What would a solution look like? I can imagine sth like _body_params->{jsonarray/items/...} = $data in the case of $data is an ARRAY - but that feels somehow dirty as it fiddles with implicit parameter defintion during requests which could collide with user parameters.

**Comment by xsawyerx** [comment]
I think we should start with defining what parameters are. In my opinion, they are essential key/value pairs. This means that any request to get parameters from a non-hash structure should fail. Having it available in `request->data` or `request->body` is fine to me and make sense.

This gives us a clear path of handling serialized content that isn't key/value pairs.

**Comment by xsawyerx** [comment]
Merged fix #937. This is now fixed.

Thanks for reporting! :+1:
