### ISSUE TITLE
website suggestion

### ISSUE THREAD

**Issue by iwelch** [PerlDancer/Dancer2#851]
it would be nice to see a basic comparison between the three major perl frameworks, catalyst, dancer2, and mojolicious.  what are they good at, what are they bad at?  possibly some examples.  this way, a new perlie does not need to learn all three to make a decision to abandon two later on.

**Comment by xsawyerx** [comment]
I'm sorry, but I do see a problem with this. Even a few. The main issue is that this is very subjective. We can talk about statistics (zero dependencies, X dependencies) but that's also off because installation time varies (Dancer2 has lots of dependencies but installs *very* quickly). The biggest issues are really a matter of taste. More or less syntax, more or less conventions, etc.

This would fit as a personal article, and many of these were written. Here is one by mst:

http://shadow.cat/blog/matt-s-trout/mstpan-1/

**Comment by iwelch** [comment]
link to a couple then?

----
Ivo Welch (ivo.welch@gmail.com)
http://www.ivo-welch.info/
J. Fred Weston Professor of Finance
Anderson School at UCLA, C519
Director, UCLA Anderson Fink Center for Finance and Investments
Free Finance Textbook, http://book.ivo-welch.info/
Editor, Critical Finance Review, http://www.critical-finance-review.org/

**Comment by xsawyerx** [comment]
Again, the problem would be a matter of personal taste. We don't all see the same comparisons. We would have our own biases and so would others.

Writing such an article for the Advent Calendar next year might not be a bad idea.
