### ISSUE TITLE
http://0:5000/ does not work

### ISSUE THREAD

**Issue by szabgab** [PerlDancer/Dancer2#862]
It might be just my browser, but after creating a new application with ```dancer -a Try::Me``` cd-ing in
and launching the server with ```plackup bin/app.psgi``` Dancer2 tells me:
```
HTTP::Server::PSGI: Accepting connections at http://0:5000/
```

but that URL does not work in my browser (Chrome on OSX). Accessing http://127.0.0.1:5000/ works.

So I am not sure what is the problem, but it is currently confusing.

**Comment by xsawyerx** [comment]
`0:5000` means "any interface on the machine, both IPv4 and IPv6". You still need some IP that the machine has. The machine doesn't have the IP "0" so that wouldn't work.

**Comment by msouth** [comment]
@szabgab Actually the text you're looking at doesn't come from Dancer, but from Plack::Runner:

     push @{$self->{options}}, server_ready => sub {
            my($args) = @_;
            my $name  = $args->{server_software} || ref($args); # $args is $server
            my $host  = $args->{host} || 0;
            my $proto = $args->{proto} || 'http';
            print STDERR "$name: Accepting connections at $proto://$host:$args->{port}/\n";
        };


However, I still wonder if there is anything we can do to make this a better experience for a new user--from their perspective, they are two steps into testing Dancer and they are presented with a URL that is non-functional.

The only thing I see off the top of my grep is that a little help could be added in the [Deployment section](https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/Manual/Deployment.pod) of the Dancer2 manual where it quotes the Plack::Runner output.  Just a little note for the user that this is not a real URL, but an indication that your app is listening on every network interface the machine supports.

Guess I should have done a p.r. instead of typing all this out :).  Gimme a bit and I'll put one in.  It will still only help people that RTFM, but I guess that's a start.

**Comment by szabgab** [comment]
@msouth that's a good idea though I think it might be better in the first example in https://metacpan.org/pod/Dancer2
