### ISSUE TITLE
Setting serializer per request path broken since 42a23b0

### ISSUE THREAD

**Issue by dboehmer** [PerlDancer/Dancer2#867]
My application needs to send plain text or data serialized as JSON depending on the request path. Last week in IRC I got the hint to do:

    hook before => sub {
        set serializer => ( request->path eq '/json' ? 'JSON' : undef );
    };

and it worked for my installed Dancer2 version. After I upgraded today it's broken: The plaintext route works fine until the JSON route is requested the first time. For the first time I get a long stack trace on the terminal and then only the JSON route continues to work.

Further investigation showed that the change 42a23b0 is the reason.

Here is a small test script I used for bisecting:

```perl
{
    package MyApp;

    use Dancer2;

    hook before => sub {
        set serializer => ( request->path eq '/json' ? 'JSON' : undef );
    };

    get '/text' => sub {return "plain text"};

    get '/json' => sub {return {format => 'JSON'} };
}

use Plack::Test;
use HTTP::Request::Common;

my $app  = Dancer2->psgi_app;
my $test = Plack::Test->create( $app );

if( $test->request( GET '/json' )->code == 200 ) {
    print "ok\n";
    exit 0;
}
else {
    print "broken\n";
    exit 1;
}
```

**Comment by beatjoerg** [comment]
+1

**Comment by veryrusty** [comment]
@dboehmer Thanks for reporting this and sorry for being tardy in following it up. I've raised #885 as part of my investigation into why you saw a change in behaviour.

Changing an apps serializer in the middle of processing a request is going to be fragile - the request object and engine attributes are set up prior to a `before` hook being called. Had you added a plugin that added a before hook in the previous version of Dancer2 you were using would have triggered the same broken outcome.

You would be better splitting you app into two, one that handles the plain text responses, the other returns the JSON responses. Then use Plack::Builder to mount the two into a single psgi app. Here's the app from your test code split that way:
```
{
    package MyApp;
    use Dancer2;
    get '/text' => sub {return "plain text"};
}

{
    package MyApp::API;
    use Dancer2;
    set serializer => 'JSON';
    get '/' => sub {return {format => 'JSON'} };
}

use Plack::Builder;
my $app = builder {
    mount '/json' => MyApp::API->to_app;
    mount '/'     => MyApp->to_app;
};
```

I hope that helps!

**Comment by xsawyerx** [comment]
I hadn't replied to it at first because I saw the example is setting the serializer on every request in the *before* hook and honestly, I was like "whoa!" Then I thought "I'll get my thoughts together and reply" and then $work got in the way. :/ Sorry about that.

My opinion:
1. I wish to fix #885, which would resolve this in turn.
2. I also wish you do not do this. :)
3. I don't wish to do extra work in supporting such a move as setting an internal component (which should be completely mutable) at run-time, on every request. I will try to resolve #885 as part of "trying to make the response lazy again", which has other benefits.

So, hopefully we'll fix it and get it working, and hopefully you'll split your app instead of doing this thing. Deal? :)

**Comment by dscoular** [comment]
Hi,
I agree with xsawyerx, I'd like to have routes which bypass the serializer if they return a SCALAR instead of a reference (or structure as you term it). The Dancer2::Cookbook documentation  hints that this will be the case:

> **Serialize outgoing responses**
> _*When you return a data structure from a route, it will automatically serialize it for you before returning it to the user.*_

It would be great if it was as simple as returning a reference for JSON and a SCALAR for text/html. It would also be nice if the content type was also respected.

Cheers,

Doug
_the big print giveth and the small print taketh away._

**Comment by veryrusty** [comment]
In general, serializers need to be able to be passed *any* perl data structure and do what they must with them. Sounds like the cookbook needs updating. 

If you wish scalars to be treated differently, and *can't* split your app, there are some _hacks_ in #952 if you have a very small number of html endpoints, or if there are many, writing a custom Dancer2 serializer that treats scalars differently is straight forward (subtle hint).

**Comment by dscoular** [comment]
Thanks all!

I split my app. Thanks for all the help... now I just need to figure out how to switch JSON pretty on and off based on the request's params.

Cheers,

Doug
_"the big print giveth and the small print taketh away"._

**Comment by xsawyerx** [comment]
Now it can also be done via the new `send_as` DSL. Does that help?

**Comment by xsawyerx** [comment]
I consider a clean solution available for this situation. If there is no additional interaction on this ticket, I intend to close it within a week.

Thank you. :)
