### ISSUE TITLE
Lack of proper learning source

### ISSUE THREAD

**Issue by krokozy** [PerlDancer/Dancer2#982]
They are all confuse and lack essential information

**Dancer::Introduction**
Why no Dancer2 ?

**perldancer.org/quickstart**

*dancer2 -a MyWeb::App*
*+ MyWeb-App/bin/app.pl*
*+ MyWeb-App/bin/app.psgi*

The above command does not create */bin/app.pl* , it only creates */bin/app.psgi* while the command "dancer" does the inverse. The information is not only wrong but confuse, i understand *psgi* is plack but what is the *.pl* ? When you install Dancer2 you also get Dancer?

 **Dancer2::Manual**
*dancer2 -a mywebapp && cd mywebapp*
*+ mywebapp/environments/production.yml*
*+ mywebapp/bin*
*+ mywebapp/bin/app.pl*
*+ mywebapp/public*

I had to stop reading at this point, as stated before it only creates  */bin/app.psgi* .
But actually i continued, then the ironic manual asks you to run *plackup -p 5000 bin/app.psgi* and it does not say where the code should be located, is it in the standard *.pm* created in */lib* or should i create a *.pl* like the Tutorial says?

**Dancer2::Tutorial**
Lots of issues here, but i will point the most elementary:
The main file is a *.pl* perl script, but can only find a *.pm* package in */lib* that seems to be the actual "root" and the tutorial has no reference to the *.pm*? 
How am i supposed to run the *.pl* if the provided run examples run the *.pm*? What is the proper file structure?
It is a copy of the Dancer tutorial, so actually there is no Dancer2 tutorial?

**Dancer2::Cookbook**
Similar issues.

**Third party sources**
Almost none, and they are not good either.

**Seriously**
What exactly is Dancer other than a simple but powerful web application framework for Perl? 

I can make my way around and write(hack) Dancer2(or Dancer?) apps with the provided info, but considering the web is a very security sensitive environment nobody should write anything for production if they don't know *exactly* what they are doing and what is going on in the internals.

**Comment by krokozy** [comment]
I can see the are lots of complaints about the Docs in Issues list. It is not only me, it is like the developers are coding the framework for themselves only.

**Comment by perldj** [comment]
I have an introductory video which will get you started in Dancer2 and
explain a lot of this here:

https://www.youtube.com/watch?v=O7dO3K-krrg

Feel free to watch that to get a good idea of where to start.
I just setup a new Dancer2 application and I did notice that the
instructions to run:

plackup -r bin/app.psgi

don't actually work, it should be:
plackup -r bin/app.pl

So someone should change http://perldancer.org/quickstart to reflect that.


David

**Comment by krokozy** [comment]
I have no background in modern frameworks and at first, after looking at most Perl frameworks  Dancer2 looked like the one i should get into.

But due to the terrible Dancer2 docs or lack of i moved my focus to Mojolicious yesterday, and while reading Mojo docs that are excellent and have some nice third party articles it was funny because while i was fully understanding Mojo i also started to understand Dancer thru' the Mojolicious docs.

But it is too late now, will stick to Mojolicious.

**Comment by xsawyerx** [comment]
@krokozy Trying to untangle the spiteful speech you have here, let me explain the situation from my perspective.

First, documentation is hard. Yes, it is super important, but unfortunately it is still not trivial.

Secondly, Dancer2 is a fork of Dancer version 1. This included the majority of version 1, which is abundant, but still needs clearing up.

Thirdly, there was and is a lot of work being done on it, but it requires a lot of coordination. We have had two outreach program interns working on the tutorial, the contributor's guide, and documentation in general. We haven't yet merged all of those.

And lastly, our time is very limited. We are not many people, and the code has a long history, and we need a lot of time to untangle the guides and improve the documentation.

Trust me that we are still not happy with the documentation. We're open about that. Having realized this is important, you're more than welcome (and we would tremendously appreciate it) to come help and contribute to it (you'll be surprised how much leeway you will get in this) instead of "contributing" this ire.

How can we move this from "this is shit" to "here's how we untangle this shit"?

**Comment by racke** [comment]
:+1: on untangle it

**Comment by krokozy2** [comment]
@xsawyerx From commom sense perspective, one should not promote a product that does not have acceptable usability conditions. it costs people time and money before they realize they were trapped for marketing. By the way the documentation mistakes are very trivial. Most of it seems to have no mistakes, just really not a good work but the mistakes are really trivial.

*"here's how we untangle this shit"?* That's an easy one, at the minimum just use the doc's of some framework considered to have good documentation as a blueprint and if possible make it even better. Mojo has a good one, not perfect but good enough. Catalyst doc's are also good but not as good in my opinion. I've heard Django docs are good but never checked it myself. The blueprint may come from any piece of unrelated software, does not need to be a web framework.

**Comment by xsawyerx** [comment]
"From commom[sic] sense perspective, one should not promote a product that does not have acceptable usability conditions. it costs people time and money before they realize they were trapped by marketing."

Are you actually saying we owe you your time and money because we didn't have enough of our own time and money to fully document something to your specifications that we released for free anyway and never ever forced you to use? Are you... kidding me?

A group of people are spending time, money, and sweat on producing something. They release it for free. You can (but don't have to) use it. You don't have to pay. You don't owe anything in return. They interact with you. You have the code, you're free to fork, you can submit pull requests, you can contribute back. You can ask for help and they will gladly assist you.

Your response to this is "You're costing me time and money because you didn't document it enough"? This has got to be the most obscene, disrespectful comment I have ever seen on an open source project, by far.

"Most of it seems to have no mistakes, just really not a good work but the mistakes are really trivial that cause a lot of confusion."

These mistakes are compounded from years of iterative work. While they're easy to fix, they're hard to spot for people who've exhausted hours and hours working on code and iterations of the documentation. Especially when people are actually *busy* with life, work, and coding, and aren't just sitting around reading the docs over and over to find mistakes they now barely notice.

Please do feel free to open pull requests to problems you see in the code (without any disrespect or ire), and you will see two things happen: 1. they get merged quickly, 2. you get a sincere thank you from us.

This offer still stands. Please, go ahead. We will still sincerely thank your contributions, and you will make this project that much better and that much easier for other people to enjoy.

Please try to also take a few minutes to consider we are **human**. We work on this project out of joy, love, and care. This isn't our paid jobs and you aren't paying for it. It doesn't cost anything to be genuinely nice to people. It doesn't cost anything to say "I think these are serious problems. I'd like to help fix them." - that would be fantastic! :)

**Comment by krokozy2** [comment]
There is no such thing as free. If one offers this piece of software at no cost that's cause one is  going to profit from it in some way that is not selling it or someone else is paying for it. Your product is no different of a paid product and subject to the same criticism and responsability.

I can fully understand you and i believe Dancer2 is likely to be a good software, but i think responsability should come before anything. 

Feel free to stop promoting your software while issues like this are not sorted out, by the way the docs look several years old as the promotion as old. I can't help with pull requests while the software is being offered and promoted to the general public without conditions for it.

**Comment by xsawyerx** [comment]
Not paying == free. It's as simple as that, no matter how philosophical you want to get.

As a paraphrase, I have a bird singing outside my house. She could be singing much more complicated tunes. I can sing along with her or I can just not listen. I cannot tell her she's selling me something and should stop offering her song unless she becomes as good as I want her to be. She's just a bird, doing her thing, singing her tune, and I am more than welcome to enjoy it if I wish.

Our "product" is different from a paid product in the word "paid". I'm not going to continue explaining the mere concept of exchanging money for something in return - I don't think you don't understand it, I think you don't wish to accept it. That's okay. I'm just not going to continue trying to explain it.

It appears your precursor to helping fix things is for us to fix all the things you want to help fix. So now we've entered the realm of circular logic.

Lastly, your entitled behavior (or your previous insulting behavior - on this and on another GH issue) is not acceptable here. I am closing this ticket and will not continue engaging with you on this.

If you would like to offer *help*, please do open a pull request. Our behavior will stay the same: your pull request will be merged shortly and we will still sincerely thank you for it. We are also, as usual, willing to help you make any contribution you wish. We welcome (respectful, non-entitlted) comments and contributions.

Have a lovely day.

**Comment by raphink** [comment]
> You gave me a car for free, and now I need to put gas in it. You lied to me. Besides, the gearbox is now broken because I don't know how to use a clutch, so you own me $3000 to fix it.
